### ISSUE TITLE
SH -todo

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sharepicgenerator#307]
- [x] logo mitte links, default, 6 Stellen
- [x] mit dreieck drunter
- [x] neue Farben
- [x] Schriftart
- [x] Claim ein und aus
- [x] Headline
- [x] Subline entweder drunter oder drüber
- [x] Sternchentext in Azo Thin
- [x] 1 Gometrie, drei Farben, Seite 4ff
